### ISSUE TITLE
Add an example showing how to use buttons to interrupt or cycle

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_LED_Animation#77]
We're lacking a simple example here or in a Learn Guide of cycling through animatiosn or interrupting animations with button pushes. Sometimes people think they need threads or interrupts to do this, but it would be good to show simple ways to accomplish that.

**Comment by kattni** [comment]
@rhooper This sounds exactly like a discussion we had recently. Perhaps you'd like to take this on!
