### ISSUE TITLE
Getting ImportError: cannot import name 'Blink' from 'adafruit_led_animation.animation'

### ISSUE THREAD

**Issue by johnsturgeon** [adafruit/Adafruit_CircuitPython_LED_Animation#92]
Just following the README.md and I get the error:
```
ImportError: cannot import name 'Blink' from 'adafruit_led_animation.animation'
```

**Comment by johnsturgeon** [comment]
I found the issue, the import should be:
`from adafruit_led_animation.animation import blink`

**Comment by dhalbert** [comment]
Sorry for that historical typo. Will fix.

**Comment by johnsturgeon** [comment]
Actually, sorry, it should be:
`from adafruit_led_animation.animation.blink import Blink`
