### ISSUE TITLE
Bug in RainbowComet when tail_length > 256 when step=0

### ISSUE THREAD

**Issue by richsad** [adafruit/Adafruit_CircuitPython_LED_Animation#95]
The rainbow comet will be a single red color comet when tail_length is > 256 and step=0. I believe this may be caused by line 63 in the source:

`        if step == 0:
            self._colorwheel_step = int(256 / tail_length)
 `
consider tail_length = > 256 and that int() statement can yield 0. When that happens the RainbowComet will be all solid red

perhaps a simple fix is:
`        if step == 0:
            self._colorwheel_step = max(int(256 / tail_length), 1)
 `

**Comment by richsad** [comment]
hmm, the code got reformatted a bit and failed to include the line feed after the if step == 0: statement

**Comment by tekktrik** [comment]
Hi @richsad, good catch, want to submit a PR for that fix?
