### ISSUE TITLE
Not all animations are called to animate within AnimationGroup

### ISSUE THREAD

**Issue by TurboVin** [adafruit/Adafruit_CircuitPython_LED_Animation#98]
group.py line 155 of method animate()
`return any(item.animate(show) for item in self._members)`
consider replacing the "any()" with "all()" so it doesn't short circuit. 

If the speed of animations is fast (0.01 for example), then the first animation in an animation group succeeds, returns true, and shortcuts without executing the remaining item.animate() commands. Thus, none of the other animations ever run. Slowing down the speed allows for more animations to run because the first few animations may skip if they haven't reached their self._next_update. So it seems sporadic, but is actually just based on timing. 

#100  submitted to fix

**Comment by Neradoc** [comment]
FIxed by #100
